apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: syfosmpapirregler
  namespace: teamsykmelding
  labels:
    team: teamsykmelding
spec:
  image: {{ image }}
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /is_alive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /is_ready
    initialDelay: 30
    periodSeconds: 5
    timeout: 1
  prometheus:
    enabled: true
    path: /prometheus
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 512Mi
  azure:
    application:
      enabled: true
      tenant: nav.no
  accessPolicy:
    inbound:
      rules:
        - application: syfosmpapirmottak
        - application: smregistrering-backend
  vault:
    enabled: true
    paths:
      - kvPath: serviceuser/data/prod/srvsyfosmpapirregler
        mountPath: /secrets/serviceuser
  webproxy: true
  ingresses:
    - "https://syfosmpapirregler.nais.adeo.no"
  env:
    - name: ALLOWED_APP_IDS
      value: 9d4d6e11-1717-44f7-b76c-1a671847bb32,88adf8ed-fed1-4022-bbc6-da222e4795eb
    - name: JWT_ISSUER
      value: https://sts.windows.net/62366534-1ec3-4962-8869-9b5535279d0b/
    - name: CLIENT_ID
      value: 77a0df77-18de-4bab-887a-ed65f5c44927
    - name: HELSENETT_SCOPE
      value: api://prod-fss.teamsykmelding.syfohelsenettproxy/.default
    - name: HELSENETT_ENDPOINT_URL
      value: https://syfohelsenettproxy.nais.adeo.no