apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: syfosmpapirregler
  namespace: default
  labels:
    team: teamsykefravr
spec:
  image: {{ image }}
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /is_alive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /is_ready
    initialDelay: 30
    periodSeconds: 5
    timeout: 5
  prometheus:
    enabled: true
    path: /prometheus
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 512Mi
  vault:
    enabled: true
  webproxy: true
  ingresses:
    - "https://syfosmpapirregler.nais.preprod.local"
  env:
    - name: ALLOWED_APP_IDS
      value: a99ce657-bce8-4f11-8dd6-5624038f4820,6e2c2c7d-9bc1-45f9-a76c-9d32b489268a
    - name: JWT_ISSUER
      value: https://sts.windows.net/966ac572-f5b7-4bbe-aa88-c76419c0f851/
    - name: CLIENT_ID
      value: c35dd346-0d3d-4b68-b883-a324c0b1098d
    - name: SECURITY_TOKEN_SERVICE_URL
      value: https://sts-q1.preprod.local/SecurityTokenServiceProvider/
    - name: HELSEPERSONELL_V1_ENDPOINT_URL
      vaule: https://pep-gw-q1.oera-q.local:9443/samhandler/helse/helsepersonell/v1
    - name: LEGE_SUSPENSJON_ENDPOINT_URL
      value: http://btsys
    - name: AADACCESSTOKEN_URL
      value: https://login.microsoftonline.com/navq.onmicrosoft.com/oauth2/token
    - name: HELSENETTPROXY_ID
      value: c18eba24-f676-47db-9a97-3c66e9304aee
    - name: HELSENETT_ENDPOINT_URL
      value: https://syfohelsenettproxy.nais.preprod.local