apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: syfosmpapirregler
  namespace: teamsykmelding
  labels:
    team: teamsykmelding
spec:
  image: {{ image }}
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /is_alive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /is_ready
    initialDelay: 30
    periodSeconds: 5
    timeout: 1
  prometheus:
    enabled: true
    path: /prometheus
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 512Mi
  azure:
    application:
      enabled: true
      tenant: trygdeetaten.no
  accessPolicy:
    inbound:
      rules:
        - application: syfosmpapirmottak
        - application: smregistrering-backend
  vault:
    enabled: true
    paths:
      - kvPath: serviceuser/data/dev/srvsyfosmpapirregler
        mountPath: /secrets/serviceuser
  webproxy: true
  ingresses:
    - "https://syfosmpapirregler.nais.preprod.local"
  kafka:
    pool: nav-dev
  env:
    - name: HELSENETT_SCOPE
      value: api://dev-fss.teamsykmelding.syfohelsenettproxy/.default
    - name: HELSENETT_ENDPOINT_URL
      value: https://syfohelsenettproxy.nais.preprod.local
    - name: SYKETILLFELLE_ENDPOINT_URL
      value: https://flex-syketilfelle.dev.intern.nav.no
    - name: SYKETILLFELLE_SCOPE
      value: api://dev-gcp.flex.flex-syketilfelle/.default