apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: syfosmpapirregler
  namespace: default
  labels:
    team: teamsykefravr
spec:
  image: {{ image }}
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /is_alive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /is_ready
    initialDelay: 30
    periodSeconds: 5
    timeout: 5
  prometheus:
    enabled: true
    path: /prometheus
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 512Mi
  vault:
    enabled: true
  webproxy: true
  ingresses:
    - "https://syfosmpapirregler.nais.adeo.no"
  env:
    - name: ALLOWED_APP_IDS
      value: 9d4d6e11-1717-44f7-b76c-1a671847bb32,88adf8ed-fed1-4022-bbc6-da222e4795eb
    - name: JWT_ISSUER
      value: https://sts.windows.net/62366534-1ec3-4962-8869-9b5535279d0b/
    - name: CLIENT_ID
      value: 77a0df77-18de-4bab-887a-ed65f5c44927
    - name: SECURITY_TOKEN_SERVICE_URL
      value: https://sts.adeo.no/SecurityTokenServiceProvider/
    - name: HELSEPERSONELL_V1_ENDPOINT_URL
      vaule: https://pep-gw.oera.no:9443/samhandler/helse/helsepersonell/v1
    - name: LEGE_SUSPENSJON_ENDPOINT_URL
      value: http://btsys
    - name: AADACCESSTOKEN_URL
      value: https://login.microsoftonline.com/navno.onmicrosoft.com/oauth2/token
    - name: HELSENETTPROXY_ID
      value: b813133d-82b8-46ef-be96-3b903ea6c048
    - name: HELSENETT_ENDPOINT_URL
      value: https://syfohelsenettproxy.nais.adeo.no