name: Deploy to dev
on:
  push:
    branches:
      - '*'
      - '!master'
jobs:
  build-push-deploy:
    name: Checkout code and create docker tag
    runs-on: ubuntu-latest
    steps:
      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: '12.0.2'
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Build and test
        run: |
          ./gradlew shadowJar test